name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:    
      
      - name: Checkout code 
        uses: actions/checkout@v2
        
      - name: Get the latest tag
        run: | 
          git fetch --prune --unshallow
      
      - name: Checkout code and build the Docker image
        run: |
          docker build --tag enivek/blazorpoc1:$(git describe --abbrev=0 --tags) .
          docker images
          
      - name: Login to Docker Registry
        run: echo $DOCKER_ACCESSTOKEN | docker login -u $DOCKER_USERNAME --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_ACCESSTOKEN: ${{ secrets.DOCKER_ACCESSTOKEN }}
        
      - name: Push to Docker Registry
        run: docker push enivek/blazorpoc1:$(git describe --abbrev=0 --tags)

